### ISSUE TITLE
Successful deletes return status code 500

### ISSUE THREAD

**Issue by wanjia09** [climatetree/stories-microservice#107]

**Comment by vpsiddhant** [comment]
Hi Wanjia, the code was updated this weekend to remove this. Are you still getting this ?

**Comment by wanjia09** [comment]
Yes, I just tested with the new endpoint "https://backend-mongo-stories.azurewebsites.net/v1/stories/delete/" + story_id, the story id is 5e94cd0e1c411a0019ac5061, but I still always get 500. 
Did the new code change got deployed?
<img width="1206" alt="Screen Shot 2020-04-13 at 1 38 18 PM" src="https://user-images.githubusercontent.com/23001250/79159111-5bf68f00-7d8c-11ea-838e-12e1a240463e.png">

**Comment by vpsiddhant** [comment]
Yeah you are write. The release was 3 days ago. I don't think it is deployed it

**Comment by vpsiddhant** [comment]
The changes are merged now
