### ISSUE TITLE
Refreshing page after a search return eror 404

### ISSUE THREAD

**Issue by vpsiddhant** [climatetree/stories-microservice#74]
Steps to reproduce:
1) Go to https://www.climatetree.wiki/
2) Type in "China"
3) Refresh page after you get result

This also happens if we directly enter something like this in url without going to the main landing page:
`https://www.climatetree.wiki/stories?storyTitle=China`

Click this to reproduce the bug:
https://www.climatetree.wiki/stories?storyTitle=China

**Comment by Hatsunespica** [comment]
Interesting error

**Comment by shwetamandavgane** [comment]
Retested this and looks fixed. So closing the defect
