### ISSUE TITLE
New story created does not appear in topStories

### ISSUE THREAD

**Issue by ranakan19** [climatetree/stories-microservice#97]
Since topStories returns n most recent stories governed by the parameter n. The new story created should appear in the top Stories.

storyId - 5e8c218c6327d9001263300c - date - 2020-04-07T06:45:31.000Z
is not returned in the top 3 Stories. Stories with timeStamp returned by the topStories are as below:

1. 5e829afed302e4b1a0d87598 - 2020-03-29T01:18:09.449Z
2. 5e829940d302e4b1a0d85a90 - 2020-03-28T10:52:11.096Z
3. 5e83e721545da9001217aed5 - 2020-04-01T00:59:09.000Z

Steps to reproduce:
1. Create a story - https://backend-mongo-stories.azurewebsites.net/stories/create
2. The created story should be returned in the Top Stories - https://backend-mongo-stories.azurewebsites.net/stories/topStories/3

**Comment by SaurabhaJirgi** [comment]
There are multiple errors in this API. Firstly I guess date is a keyword that is causing a problem. Secondly, the format which is being stored although displayed as "2020-03-29T01:18:09.449Z", it is stored as "04/14/2017 11:16 PM" by mongodb.

As the API sorts by date and this date is in string format, it is giving preference to month followed by date followed by year while sorting.

These two reasons are causing the failure of the API.

We now have to see how ES handles this and make changes to the code accordingly as this API is being moved to ES.

**Comment by ranakan19** [comment]
why is the year 2017 though?

**Comment by ranakan19** [comment]
When the request body has following:
{
	"posted_by": "testUser",
	"user_id" : 323,
	"hyperlink" : "https://ipcc.ch/climate/",
	"rating" : 3,
	"story_title" : "Test Story for date check",
	"place_ids" : [3,5],
	"media_type" : "article",
	"date" : "04/16/2020 01:12 AM",
	"solution" : ["LED Lighting (Household)","Landfill Methane","Landfill Methane"],
	"comments" : [],
	"liked_by_users": [],
    "flagged_by_users": []
}

the story created is able to format is properly as in the response:
 "date": "2020-04-16T05:12:00.000Z"

**Comment by ranakan19** [comment]
works locally, able to sort, could it be another cosmosdb issue?

**Comment by SaurabhaJirgi** [comment]
The year 2017 was just an example I took to show the format in which the date is stored.
Let us get on a call to discuss this?

**Comment by SaurabhaJirgi** [comment]
Checked with ES and an old commit. Seems to be working fine now. ES had a small typo error which was fixed with https://github.com/climatetree/stories-microservice/pull/119
